stages:
  - build-natives
  - build-java

jobs:
  include:
    - stage: build-natives
      filter_secrets: false
      name: "Windows MSVC Natives"
      os: windows
      language: shell
      before_install:
        - shopt -s expand_aliases
      install:
        - |
          choco install awscli
          alias aws="/c/Program\ Files/Amazon/AWSCLI/bin/aws.exe "
          choco install cmake --version 3.13.0
          choco install jdk8
          choco install visualstudio2017buildtools
          choco install visualstudio2017-workload-vctools
          choco install visualstudio2017-workload-nativedesktop
      script:
        - mkdir build && cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=RelWithDebInfo ../native || cat CMakeFiles/CMakeOutput.log
        - cmake --build .
      after_success:
        - |
          mkdir -p artifacts/windows
          cp DriftFX/RelWithDebInfo/driftfx.{dll,lib,pdb} artifacts/windows
          cp samples/RelWithDebInfo/samples.{dll,lib,pdb} artifacts/windows
          aws s3 cp --recursive artifacts/windows s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/natives/
    - name: "MacOS GCC Natives"
      os: osx
      language: cpp
      addons:
        homebrew:
          packages:
            - awscli
          update: true
      install:
        - |
          chmod +x tools/install_cmake_macos.sh
          tools/install_cmake_macos.sh
          PATH=${TRAVIS_BUILD_DIR}/cmake.portable/CMake.app/Contents/bin:${PATH}
          echo $PATH
      script:
        - mkdir build && cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo ../native || cat CMakeFiles/CMakeOutput.log
        - cmake --build .
      after_success:
        - |
          mkdir -p artifacts/macos
          cp DriftFX/libdriftfx.dylib artifacts/macos
          cp -r DriftFX/libdriftfx.dylib.dSYM artifacts/macos
          cp samples/libsamples.dylib artifacts/macos
          cp samples/libsamples.dylib.dSYM artifacts/macos
          aws s3 cp --recursive artifacts/macos s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/natives/
    - name: "Linux GCC Natives"
      os: linux
      dist: trusty
      language: cpp
      compiler:
        - gcc
      before_install:
        - |
          pip install --user awscli
          pip install --user cmake==3.13.0
      script:
        - mkdir build && cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo ../native || cat CMakeFiles/CMakeOutput.log
        - cmake --build .
      after_success:
        - |
          mkdir -p artifacts/linux
          cp DriftFX/libdriftfx.so{,.debug} artifacts/linux
          cp samples/libsamples.so{,.debug} artifacts/linux
          aws s3 cp --recursive artifacts/linux s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/natives/
    - stage: build-java
      name: "Java Build"
      os: linux
      dist: trusty
      language: java
      cache:
        directories:
        - $HOME/.m2
      before_install:
        - pip install --user awscli
      install:
        - |
          aws s3 cp --recursive s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/natives .
          rm org.eclipse.fx.drift/native/*
          cp natives/libdriftfx.{so,dylib} driftfx.dll org.eclipse.fx.drift/native/
          rm org.eclipse.fx.drift.samples/native/*
          cp naitves/libsamples.{so,dylib} samples.dll org.eclipse.fx.drift.samples/native/
          
          ls -al org.eclipse.fx.drift/native
          ls -al org.eclipse.fx.drift.samples/native
      script: 
        - |
          mkdir dist
          zip -r dist/sources.zip native org.eclipse.fx.drift org.eclipse.fx.drift.feature org.eclipse.fx.drift.samples org.eclipse.fx.drift.samples.feature org.eclipse.fx.drift.updatesite 
        - |
          mvn clean package
      after_success:
        - |
          aws s3 cp org.eclipse.fx.drift.updatesite/target/org.eclipse.fx.drift.updatesite-0.1.0-SNAPSHOT.zip s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/updatesite.zip
          echo "$TRAVIS_COMMIT" > git_commit
          aws s3 cp git_commit s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/git_commit
          mkdir dist
          mkdir dist/include
          cp -R native/DriftFX/include/* dist/include/
          mkdir dist/libs
          cp -r natives/* dist/libs/
          cp git_commit dist/git_commit
          zip -r dist.zip dist/*
          aws s3 cp dist.zip s3://efxclipse-drift/$TRAVIS_BUILD_NUMBER/dist.zip
          wget "$WEBHOOK_URL?token=$WEBHOOK_TOKEN&token0=$AWS_ACCESS_KEY_ID&token1=$AWS_SECRET_ACCESS_KEY&travisBuildNumber=$TRAVIS_BUILD_NUMBER&branch_name=$TRAVIS_BRANCH"
